source "https://rubygems.org"

gem "activesupport"
gem "csv"
gem "erubis"
gem "icalendar"
gem "nokogiri"
gem "pry-byebug"
gem "psych", "5.2.2"
gem "rake"
gem "require_all"
gem "rspec"
gem "rubocop"
gem "rubocop-rake"
gem "rubocop-rspec"
gem "sorbet-runtime"
